version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  proyecto-reactivo:
    build:
      dockerfile: Dockerfile
    image: proyecto-reactivo
    container_name: proyecto-reactivo
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - URL=r2dbc:postgresql://db:5432/postgres
      - USERNAME=postgres
      - PASSWORD=postgres
      - SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - EXPIRATION=86400000
      - REFRESH_TOKEN_EXPIRATION=604800000
    depends_on:
      - db